### ISSUE TITLE
楼主这个仓库get不到呀

### ISSUE THREAD

**Issue by Gundam0079** [yhaolpz/ByteXPlugin#1]
如题
https://raw.githubusercontent.com
jcenter仓库也没搞下来
下面是访问不到的 难道是我的网络问题？

**Comment by yhaolpz** [comment]
> 如题
> https://raw.githubusercontent.com
> jcenter仓库也没搞下来
> 下面是访问不到的 难道是我的网络问题？

亲测过是 ok 的哦，应该是你的网络问题了。
